# Generated by Django 5.0.1 on 2024-08-29 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_discussion_img_discussion_topic'),
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.student'),
        ),
    ]
